// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get": {
            "get": {
                "description": "Get info about perfumes. Can accept brand and name parameters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perfumes"
                ],
                "summary": "Get list of perfumes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Brand of the perfume",
                        "name": "brand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Name of the perfume",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found perfumes",
                        "schema": {
                            "$ref": "#/definitions/responses.PerfumeCollection"
                        }
                    },
                    "204": {
                        "description": "No perfumes found"
                    }
                }
            }
        },
        "/update": {
            "post": {
                "description": "Update database state about perfumes. Can truncate table",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Perfumes"
                ],
                "summary": "Update perfumes",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Is hard update",
                        "name": "hard",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password for hard update",
                        "name": "password",
                        "in": "query"
                    },
                    {
                        "description": "List of perfumes to update",
                        "name": "perfumes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/responses.PerfumeCollection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update successful"
                    },
                    "400": {
                        "description": "Wrong perfumes format"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Perfume": {
            "type": "object",
            "properties": {
                "base_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "brand": {
                    "type": "string"
                },
                "family": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "middle_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "upper_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "volumes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "responses.PerfumeCollection": {
            "type": "object",
            "properties": {
                "perfumes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Perfume"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/perfumes",
	Schemes:          []string{},
	Title:            "Perfume DB API",
	Description:      "Microservice which operates over perfume database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
