// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/perfume": {
            "get": {
                "description": "Get suggests for perfumes. Accept brand and name and recommends 4+- perfumes which user probably will like.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perfumes"
                ],
                "summary": "Suggests some perfumes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Brand of the perfume which you like",
                        "name": "brand",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the perfume which you like",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Suggested perfumes",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuggestResponse"
                        }
                    },
                    "204": {
                        "description": "No perfumes found for suggestion",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuggestResponse"
                        }
                    },
                    "400": {
                        "description": "Incorrect parameters",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuggestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuggestResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.SuggestResponse": {
            "type": "object",
            "properties": {
                "input": {
                    "$ref": "#/definitions/handlers.inputPerfume"
                },
                "success": {
                    "type": "boolean"
                },
                "suggested": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.rankedPerfumeWithProps"
                    }
                }
            }
        },
        "handlers.inputPerfume": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "handlers.rankedPerfumeWithProps": {
            "type": "object",
            "properties": {
                "perfume": {
                    "$ref": "#/definitions/models.GluedPerfume"
                },
                "rank": {
                    "type": "integer"
                }
            }
        },
        "models.GluedPerfume": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "$ref": "#/definitions/models.PerfumeProperties"
                }
            }
        },
        "models.PerfumeProperties": {
            "type": "object",
            "properties": {
                "base_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "family": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "middle_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sex": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "upper_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/suggest",
	Schemes:          []string{},
	Title:            "Perfume Suggestion Service",
	Description:      "Mircoservice with bussiness logic for perfume suggestions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
